# Copyright (c) 2009-2010 Satoshi Nakamoto
# Distributed under the MIT/X11 software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

# :=0 --> UPnP support turned off by default at runtime
# :=1 --> UPnP support turned on by default at runtime
# :=- --> No UPnP support - miniupnp not required
USE_UPNP:=-

# :=1 --> Enable IPv6 support
# :=0 --> Disable IPv6 support
USE_IPV6:=1

# Retain the historical wallet database format.
BDB_LIB_SUFFIX ?= -4.8

LINK:=$(CXX)

DEFS=-DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64

DEFS += $(addprefix -I,$(CURDIR) $(CURDIR)/obj/build5 $(BDB_INCLUDE_PATH) $(BOOST_INCLUDE_PATH) $(OPENSSL_INCLUDE_PATH))
LIBS = $(addprefix -L,$(BDB_LIB_PATH) $(BOOST_LIB_PATH) $(OPENSSL_LIB_PATH)) -l pthread -l boost_system -l boost_program_options -l boost_thread -l boost_filesystem -l boost_chrono -l cryptopp

LMODE = dynamic
LMODE2 = dynamic
ifdef STATIC
    LMODE = static
    ifeq (${STATIC}, all)
        LMODE2 = static
    endif
endif

# for boost 1.37, add -mt to the boost libraries
LIBS += \
 -Wl,-B$(LMODE) \
   -l db_cxx$(BDB_LIB_SUFFIX) \
   -l ssl \
   -l crypto

TESTLIBS = $(addprefix -L,$(BOOST_LIB_PATH) $(OPENSSL_LIB_PATH)) -lboost_thread -lboost_system -lcrypto -lcryptopp -pthread

ifndef USE_UPNP
	override USE_UPNP = -
endif
ifneq (${USE_UPNP}, -)
	LIBS += /usr/lib/libminiupnpc.a
	DEFS += -DUSE_UPNP=$(USE_UPNP)
endif

ifneq (${USE_IPV6}, -)
	DEFS += -DUSE_IPV6=$(USE_IPV6)
endif

LIBS+= \
 -Wl,-B$(LMODE2) \
   -l z \
   -l dl \
   -l pthread


# Hardening
# Make some classes of vulnerabilities unexploitable in case one is discovered.
#
    # This is a workaround for Ubuntu bug #691722, the default -fstack-protector causes
    # -fstack-protector-all to be ignored unless -fno-stack-protector is used first.
    # see: https://bugs.launchpad.net/ubuntu/+source/gcc-4.5/+bug/691722
    HARDENING=-fno-stack-protector

    # Stack Canaries
    # Put numbers at the beginning of each stack frame and check that they are the same.
    # If a stack buffer if overflowed, it writes over the canary number and then on return
    # when that number is checked, it won't be the same and the program will exit with
    # a "Stack smashing detected" error instead of being exploited.
    HARDENING+=-fstack-protector-all -Wstack-protector

    # Make some important things such as the global offset table read only as soon as
    # the dynamic linker is finished building it. This will prevent overwriting of addresses
    # which would later be jumped to.
    LDHARDENING+=-Wl,-z,relro -Wl,-z,now

    # Build position independent code to take advantage of Address Space Layout Randomization
    # offered by some kernels.
    # see doc/build-unix.txt for more information.
    ifdef PIE
        HARDENING+=-fPIE
        LDHARDENING+=-pie
    endif

    # -D_FORTIFY_SOURCE=2 does some checking for potentially exploitable code patterns in
    # the source such overflowing a statically defined buffer.
    HARDENING+=-D_FORTIFY_SOURCE=2
#


DEBUGFLAGS=-g

# CXXFLAGS can be specified on the make command line, so we use xCXXFLAGS that only
# adds some defaults in front. Unfortunately, CXXFLAGS=... $(CXXFLAGS) does not work.
xCXXFLAGS=-std=c++11 -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -Wno-unused-variable \
    $(DEBUGFLAGS) $(DEFS) $(HARDENING) $(CXXFLAGS)

# LDFLAGS can be specified on the make command line, so we use xLDFLAGS that only
# adds some defaults in front. Unfortunately, LDFLAGS=... $(LDFLAGS) does not work.
xLDFLAGS=$(LDHARDENING) $(LDFLAGS)

OBJS= \
    leveldb/libleveldb.a \
    obj/alert.o \
    obj/version.o \
    obj/checkpoints.o \
    obj/netbase.o \
    obj/addrman.o \
    obj/crypter.o \
    obj/key.o \
    obj/db.o \
    obj/init.o \
    obj/keystore.o \
    obj/main.o \
    obj/net.o \
    obj/protocol.o \
    obj/bitcoinrpc.o \
    obj/rpcdump.o \
    obj/rpcnet.o \
    obj/rpcmining.o \
    obj/rpcwallet.o \
    obj/rpcblockchain.o \
    obj/rpcrawtransaction.o \
    obj/script.o \
    obj/sync.o \
    obj/util.o \
    obj/wallet.o \
    obj/walletdb.o \
    obj/hash.o \
    obj/bloom.o \
    obj/noui.o \
    obj/leveldb.o \
    obj/txdb.o\
    obj/keccak.o


all: obj Slothcoind

test check: check-security

#
# LevelDB support
#
MAKEOVERRIDES =
LIBS += $(CURDIR)/leveldb/libleveldb.a $(CURDIR)/leveldb/libmemenv.a

DEFS += $(addprefix -I,$(CURDIR)/leveldb/include)
DEFS += $(addprefix -I,$(CURDIR)/leveldb/helpers)
leveldb/libleveldb.a:
	@echo "Building LevelDB ..." && cd leveldb && $(MAKE) CC=$(CC) CXX=$(CXX) OPT="$(xCXXFLAGS)" libleveldb.a libmemenv.a && cd ..

# auto-generated dependencies:
-include obj/*.d

$(CURDIR)/obj/build5/build.h: FORCE
	mkdir -p obj/build5
	/bin/sh ../share/genbuild.sh obj/build5/build.h
obj/version.o: $(CURDIR)/obj/build5/build.h
DEFS += -DHAVE_BUILD_INFO

obj/%.o: %.cpp makefile.unix | obj
	$(CXX) -c $(xCXXFLAGS) -MMD -MP -MF $(@:%.o=%.d) -o $@ $<

obj/%.o: %.c makefile.unix | obj
	$(CXX) -c $(xCXXFLAGS) -fpermissive -MMD -MP -MF $(@:%.o=%.d) -o $@ $<

obj:
	-mkdir -p obj

Slothcoind: $(OBJS:obj/%=obj/%)
	$(LINK) $(xCXXFLAGS) -o $@ $^ $(xLDFLAGS) $(LIBS)

clean:
	-rm -f Slothcoind security_tests security_tests_sanitized
	-rm -f obj/*.o
	-rm -f obj-test/*.o
	-rm -f obj/*.d
	-rm -f obj-test/*.P
	-rm -f obj/build5/build.h
	-cd leveldb && $(MAKE) clean || true

FORCE:

# Focused tests do not start the node or touch a wallet directory.
security_tests: test/security_tests.cpp obj/key.o obj/crypter.o obj/keccak.o $(wildcard *.h)
	$(CXX) $(xCXXFLAGS) -o $@ test/security_tests.cpp obj/key.o obj/crypter.o obj/keccak.o $(xLDFLAGS) $(TESTLIBS)

check-security: security_tests
	./security_tests

security_tests_sanitized: test/security_tests.cpp key.cpp crypter.cpp obj/keccak.o $(wildcard *.h)
	$(CXX) $(xCXXFLAGS) -O1 -fsanitize=address,undefined -fno-omit-frame-pointer -o $@ test/security_tests.cpp key.cpp crypter.cpp obj/keccak.o $(xLDFLAGS) $(TESTLIBS)

check-security-sanitized: security_tests_sanitized
	./security_tests_sanitized

.PHONY: all test check check-security check-security-sanitized clean FORCE
